name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # Atualizado de v3 para v4
        uses: actions/checkout@v4

      - name: FTP Deploy
        # Atualizado de v4.3.4 para v4.3.5 (ou a última estável)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: public_html/